// Code generated by goctl. DO NOT EDIT!
// Source: msg_gateway.proto

package gateway

import (
	"context"

	"github.com/wymli/bcsns/app/msg_gateway/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PushMsgReq  = pb.PushMsgReq
	PushMsgResp = pb.PushMsgResp

	Gateway interface {
		PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error)
	}

	defaultGateway struct {
		cli zrpc.Client
	}
)

func NewGateway(cli zrpc.Client) Gateway {
	return &defaultGateway{
		cli: cli,
	}
}

func (m *defaultGateway) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error) {
	client := pb.NewGatewayClient(m.cli.Conn())
	return client.PushMsg(ctx, in, opts...)
}
