// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	message "github.com/wymli/bcsns/app/message_api/internal/handler/message"
	"github.com/wymli/bcsns/app/message_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat/user",
				Handler: message.SendUserMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat/room",
				Handler: message.SendRoomMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/moments",
				Handler: message.PostMomentsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
