// Code generated by goctl. DO NOT EDIT!
// Source: msg_gateway.proto

package server

import (
	"context"

	"github.com/wymli/bcsns/app/msg_gateway/rpc/biz/logic"
	"github.com/wymli/bcsns/app/msg_gateway/svc"
	"github.com/wymli/bcsns/app/msg_gateway/rpc/pb"
)

type GatewayServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGatewayServer
}

func NewGatewayServer(svcCtx *svc.ServiceContext) *GatewayServer {
	return &GatewayServer{
		svcCtx: svcCtx,
	}
}

func (s *GatewayServer) PushUserMsg(ctx context.Context, in *pb.PushUserMsgReq) (*pb.PushUserMsgResp, error) {
	l := logic.NewPushUserMsgLogic(ctx, s.svcCtx)
	return l.PushUserMsg(in)
}

func (s *GatewayServer) PushRoomMsg(ctx context.Context, in *pb.PushRoomMsgReq) (*pb.PushRoomMsgResp, error) {
	l := logic.NewPushRoomMsgLogic(ctx, s.svcCtx)
	return l.PushRoomMsg(in)
}

func (s *GatewayServer) BatchPushUserMsg(ctx context.Context, in *pb.BatchPushUserMsgReq) (*pb.BatchPushUserMsgResp, error) {
	l := logic.NewBatchPushUserMsgLogic(ctx, s.svcCtx)
	return l.BatchPushUserMsg(in)
}

func (s *GatewayServer) BatchPushRoomMsg(ctx context.Context, in *pb.BatchPushRoomMsgReq) (*pb.BatchPushRoomMsgResp, error) {
	l := logic.NewBatchPushRoomMsgLogic(ctx, s.svcCtx)
	return l.BatchPushRoomMsg(in)
}

func (s *GatewayServer) BatchNotify(ctx context.Context, in *pb.BatchNotifyReq) (*pb.BatchNotifyResp, error) {
	l := logic.NewBatchNotifyLogic(ctx, s.svcCtx)
	return l.BatchNotify(in)
}
