// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: notify.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyType int32

const (
	NotifyType_UNKNOWN          NotifyType = 0
	NotifyType_MSG_ON_CHAIN     NotifyType = 1
	NotifyType_MOMENTS_ON_CHAIN NotifyType = 2
	NotifyType_MSG_READ         NotifyType = 3
	NotifyType_FRIENDS_ONLINE   NotifyType = 4
	NotifyType_FOLLOWS_ONLINE   NotifyType = 5
)

// Enum value maps for NotifyType.
var (
	NotifyType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MSG_ON_CHAIN",
		2: "MOMENTS_ON_CHAIN",
		3: "MSG_READ",
		4: "FRIENDS_ONLINE",
		5: "FOLLOWS_ONLINE",
	}
	NotifyType_value = map[string]int32{
		"UNKNOWN":          0,
		"MSG_ON_CHAIN":     1,
		"MOMENTS_ON_CHAIN": 2,
		"MSG_READ":         3,
		"FRIENDS_ONLINE":   4,
		"FOLLOWS_ONLINE":   5,
	}
)

func (x NotifyType) Enum() *NotifyType {
	p := new(NotifyType)
	*p = x
	return p
}

func (x NotifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_proto_enumTypes[0].Descriptor()
}

func (NotifyType) Type() protoreflect.EnumType {
	return &file_notify_proto_enumTypes[0]
}

func (x NotifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyType.Descriptor instead.
func (NotifyType) EnumDescriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

type NotifyId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//	*NotifyId_UserId
	//	*NotifyId_MsgId
	Id isNotifyId_Id `protobuf_oneof:"id"`
}

func (x *NotifyId) Reset() {
	*x = NotifyId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyId) ProtoMessage() {}

func (x *NotifyId) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyId.ProtoReflect.Descriptor instead.
func (*NotifyId) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

func (m *NotifyId) GetId() isNotifyId_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *NotifyId) GetUserId() uint64 {
	if x, ok := x.GetId().(*NotifyId_UserId); ok {
		return x.UserId
	}
	return 0
}

func (x *NotifyId) GetMsgId() int64 {
	if x, ok := x.GetId().(*NotifyId_MsgId); ok {
		return x.MsgId
	}
	return 0
}

type isNotifyId_Id interface {
	isNotifyId_Id()
}

type NotifyId_UserId struct {
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof"`
}

type NotifyId_MsgId struct {
	MsgId int64 `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3,oneof"`
}

func (*NotifyId_UserId) isNotifyId_Id() {}

func (*NotifyId_MsgId) isNotifyId_Id() {}

type NotifyRecvId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RecvId:
	//	*NotifyRecvId_UserId
	//	*NotifyRecvId_RoomId
	RecvId isNotifyRecvId_RecvId `protobuf_oneof:"recv_id"`
}

func (x *NotifyRecvId) Reset() {
	*x = NotifyRecvId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyRecvId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRecvId) ProtoMessage() {}

func (x *NotifyRecvId) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRecvId.ProtoReflect.Descriptor instead.
func (*NotifyRecvId) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{1}
}

func (m *NotifyRecvId) GetRecvId() isNotifyRecvId_RecvId {
	if m != nil {
		return m.RecvId
	}
	return nil
}

func (x *NotifyRecvId) GetUserId() uint64 {
	if x, ok := x.GetRecvId().(*NotifyRecvId_UserId); ok {
		return x.UserId
	}
	return 0
}

func (x *NotifyRecvId) GetRoomId() uint64 {
	if x, ok := x.GetRecvId().(*NotifyRecvId_RoomId); ok {
		return x.RoomId
	}
	return 0
}

type isNotifyRecvId_RecvId interface {
	isNotifyRecvId_RecvId()
}

type NotifyRecvId_UserId struct {
	UserId uint64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof"`
}

type NotifyRecvId_RoomId struct {
	RoomId uint64 `protobuf:"varint,4,opt,name=room_id,json=roomId,proto3,oneof"`
}

func (*NotifyRecvId_UserId) isNotifyRecvId_RecvId() {}

func (*NotifyRecvId_RoomId) isNotifyRecvId_RecvId() {}

var File_notify_proto protoreflect.FileDescriptor

var file_notify_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0x44, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0x4f, 0x0a, 0x0c,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x76, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x69, 0x64, 0x2a, 0x77, 0x0a,
	0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x53, 0x47, 0x5f,
	0x4f, 0x4e, 0x5f, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x4f,
	0x4d, 0x45, 0x4e, 0x54, 0x53, 0x5f, 0x4f, 0x4e, 0x5f, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x10, 0x03, 0x12, 0x12,
	0x0a, 0x0e, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x53, 0x5f, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45,
	0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x53, 0x5f, 0x4f, 0x4e,
	0x4c, 0x49, 0x4e, 0x45, 0x10, 0x05, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x79, 0x6d, 0x6c, 0x69, 0x2f, 0x62, 0x63, 0x73, 0x6e, 0x73,
	0x2f, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x2f, 0x70, 0x62, 0x2f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x3b, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notify_proto_rawDescOnce sync.Once
	file_notify_proto_rawDescData = file_notify_proto_rawDesc
)

func file_notify_proto_rawDescGZIP() []byte {
	file_notify_proto_rawDescOnce.Do(func() {
		file_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_notify_proto_rawDescData)
	})
	return file_notify_proto_rawDescData
}

var file_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notify_proto_goTypes = []interface{}{
	(NotifyType)(0),      // 0: notify.NotifyType
	(*NotifyId)(nil),     // 1: notify.NotifyId
	(*NotifyRecvId)(nil), // 2: notify.NotifyRecvId
}
var file_notify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notify_proto_init() }
func file_notify_proto_init() {
	if File_notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyRecvId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_notify_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NotifyId_UserId)(nil),
		(*NotifyId_MsgId)(nil),
	}
	file_notify_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*NotifyRecvId_UserId)(nil),
		(*NotifyRecvId_RoomId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notify_proto_goTypes,
		DependencyIndexes: file_notify_proto_depIdxs,
		EnumInfos:         file_notify_proto_enumTypes,
		MessageInfos:      file_notify_proto_msgTypes,
	}.Build()
	File_notify_proto = out.File
	file_notify_proto_rawDesc = nil
	file_notify_proto_goTypes = nil
	file_notify_proto_depIdxs = nil
}
