// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: msg_pull.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 内容类型
	ServerMsgId int64  `protobuf:"varint,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	SendUserId  uint64 `protobuf:"varint,4,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"` // sender user id
	RoomId      uint64 `protobuf:"varint,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`               // group id if it is a group chat
	Data        []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`                                  // payload body
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_pull_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_msg_pull_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_msg_pull_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Message) GetServerMsgId() int64 {
	if x != nil {
		return x.ServerMsgId
	}
	return 0
}

func (x *Message) GetSendUserId() uint64 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *Message) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Moments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 内容类型
	ServerMsgId int64  `protobuf:"varint,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	SendUserId  uint64 `protobuf:"varint,4,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"` // sender user id
	Data        []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`                                  // payload body
}

func (x *Moments) Reset() {
	*x = Moments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_pull_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Moments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moments) ProtoMessage() {}

func (x *Moments) ProtoReflect() protoreflect.Message {
	mi := &file_msg_pull_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moments.ProtoReflect.Descriptor instead.
func (*Moments) Descriptor() ([]byte, []int) {
	return file_msg_pull_proto_rawDescGZIP(), []int{1}
}

func (x *Moments) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Moments) GetServerMsgId() int64 {
	if x != nil {
		return x.ServerMsgId
	}
	return 0
}

func (x *Moments) GetSendUserId() uint64 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *Moments) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PullLatestMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalMsgId int64 `protobuf:"varint,1,opt,name=local_msg_id,json=localMsgId,proto3" json:"local_msg_id,omitempty"`
}

func (x *PullLatestMsgReq) Reset() {
	*x = PullLatestMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_pull_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullLatestMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullLatestMsgReq) ProtoMessage() {}

func (x *PullLatestMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_pull_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullLatestMsgReq.ProtoReflect.Descriptor instead.
func (*PullLatestMsgReq) Descriptor() ([]byte, []int) {
	return file_msg_pull_proto_rawDescGZIP(), []int{2}
}

func (x *PullLatestMsgReq) GetLocalMsgId() int64 {
	if x != nil {
		return x.LocalMsgId
	}
	return 0
}

type PullLatestMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgList []*Message `protobuf:"bytes,1,rep,name=msg_list,json=msgList,proto3" json:"msg_list,omitempty"`
}

func (x *PullLatestMsgResp) Reset() {
	*x = PullLatestMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_pull_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullLatestMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullLatestMsgResp) ProtoMessage() {}

func (x *PullLatestMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_pull_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullLatestMsgResp.ProtoReflect.Descriptor instead.
func (*PullLatestMsgResp) Descriptor() ([]byte, []int) {
	return file_msg_pull_proto_rawDescGZIP(), []int{3}
}

func (x *PullLatestMsgResp) GetMsgList() []*Message {
	if x != nil {
		return x.MsgList
	}
	return nil
}

type PullLatestMomentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalMomentId int64 `protobuf:"varint,1,opt,name=local_moment_id,json=localMomentId,proto3" json:"local_moment_id,omitempty"`
}

func (x *PullLatestMomentsReq) Reset() {
	*x = PullLatestMomentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_pull_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullLatestMomentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullLatestMomentsReq) ProtoMessage() {}

func (x *PullLatestMomentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_pull_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullLatestMomentsReq.ProtoReflect.Descriptor instead.
func (*PullLatestMomentsReq) Descriptor() ([]byte, []int) {
	return file_msg_pull_proto_rawDescGZIP(), []int{4}
}

func (x *PullLatestMomentsReq) GetLocalMomentId() int64 {
	if x != nil {
		return x.LocalMomentId
	}
	return 0
}

type PullLatestMomentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MomentsList []*Moments `protobuf:"bytes,1,rep,name=moments_list,json=momentsList,proto3" json:"moments_list,omitempty"`
}

func (x *PullLatestMomentsResp) Reset() {
	*x = PullLatestMomentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_pull_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullLatestMomentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullLatestMomentsResp) ProtoMessage() {}

func (x *PullLatestMomentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_pull_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullLatestMomentsResp.ProtoReflect.Descriptor instead.
func (*PullLatestMomentsResp) Descriptor() ([]byte, []int) {
	return file_msg_pull_proto_rawDescGZIP(), []int{5}
}

func (x *PullLatestMomentsResp) GetMomentsList() []*Moments {
	if x != nil {
		return x.MomentsList
	}
	return nil
}

var File_msg_pull_proto protoreflect.FileDescriptor

var file_msg_pull_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x70, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9f, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x6e,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x07, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73,
	0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34, 0x0a,
	0x10, 0x50, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x11, 0x50, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x3e, 0x0a, 0x14, 0x50, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x5f, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x47, 0x0a, 0x15, 0x50, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x0c, 0x6d, 0x6f, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0b, 0x6d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xd3, 0x01, 0x0a, 0x07, 0x4d, 0x73,
	0x67, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x5b, 0x0a, 0x0d, 0x50, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x6c, 0x6c,
	0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x3a,
	0x01, 0x2a, 0x12, 0x6b, 0x0a, 0x11, 0x50, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x6c,
	0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x3a, 0x01, 0x2a, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_pull_proto_rawDescOnce sync.Once
	file_msg_pull_proto_rawDescData = file_msg_pull_proto_rawDesc
)

func file_msg_pull_proto_rawDescGZIP() []byte {
	file_msg_pull_proto_rawDescOnce.Do(func() {
		file_msg_pull_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_pull_proto_rawDescData)
	})
	return file_msg_pull_proto_rawDescData
}

var file_msg_pull_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_msg_pull_proto_goTypes = []interface{}{
	(*Message)(nil),               // 0: pb.Message
	(*Moments)(nil),               // 1: pb.Moments
	(*PullLatestMsgReq)(nil),      // 2: pb.PullLatestMsgReq
	(*PullLatestMsgResp)(nil),     // 3: pb.PullLatestMsgResp
	(*PullLatestMomentsReq)(nil),  // 4: pb.PullLatestMomentsReq
	(*PullLatestMomentsResp)(nil), // 5: pb.PullLatestMomentsResp
}
var file_msg_pull_proto_depIdxs = []int32{
	0, // 0: pb.PullLatestMsgResp.msg_list:type_name -> pb.Message
	1, // 1: pb.PullLatestMomentsResp.moments_list:type_name -> pb.Moments
	2, // 2: pb.MsgPull.PullLatestMsg:input_type -> pb.PullLatestMsgReq
	4, // 3: pb.MsgPull.PullLatestMoments:input_type -> pb.PullLatestMomentsReq
	3, // 4: pb.MsgPull.PullLatestMsg:output_type -> pb.PullLatestMsgResp
	5, // 5: pb.MsgPull.PullLatestMoments:output_type -> pb.PullLatestMomentsResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_msg_pull_proto_init() }
func file_msg_pull_proto_init() {
	if File_msg_pull_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_pull_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_pull_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Moments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_pull_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullLatestMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_pull_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullLatestMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_pull_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullLatestMomentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_pull_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullLatestMomentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_pull_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_pull_proto_goTypes,
		DependencyIndexes: file_msg_pull_proto_depIdxs,
		MessageInfos:      file_msg_pull_proto_msgTypes,
	}.Build()
	File_msg_pull_proto = out.File
	file_msg_pull_proto_rawDesc = nil
	file_msg_pull_proto_goTypes = nil
	file_msg_pull_proto_depIdxs = nil
}
