// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: message.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageClient interface {
	SendUserMsg(ctx context.Context, in *SendUserMsgReq, opts ...grpc.CallOption) (*SendUserMsgResp, error)
	SendRoomMsg(ctx context.Context, in *SendRoomMsgReq, opts ...grpc.CallOption) (*SendRoomMsgResp, error)
	PostMoments(ctx context.Context, in *PostMomentsReq, opts ...grpc.CallOption) (*PostMomentsResp, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) SendUserMsg(ctx context.Context, in *SendUserMsgReq, opts ...grpc.CallOption) (*SendUserMsgResp, error) {
	out := new(SendUserMsgResp)
	err := c.cc.Invoke(ctx, "/pb.message/SendUserMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SendRoomMsg(ctx context.Context, in *SendRoomMsgReq, opts ...grpc.CallOption) (*SendRoomMsgResp, error) {
	out := new(SendRoomMsgResp)
	err := c.cc.Invoke(ctx, "/pb.message/SendRoomMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) PostMoments(ctx context.Context, in *PostMomentsReq, opts ...grpc.CallOption) (*PostMomentsResp, error) {
	out := new(PostMomentsResp)
	err := c.cc.Invoke(ctx, "/pb.message/PostMoments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
// All implementations must embed UnimplementedMessageServer
// for forward compatibility
type MessageServer interface {
	SendUserMsg(context.Context, *SendUserMsgReq) (*SendUserMsgResp, error)
	SendRoomMsg(context.Context, *SendRoomMsgReq) (*SendRoomMsgResp, error)
	PostMoments(context.Context, *PostMomentsReq) (*PostMomentsResp, error)
	mustEmbedUnimplementedMessageServer()
}

// UnimplementedMessageServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (UnimplementedMessageServer) SendUserMsg(context.Context, *SendUserMsgReq) (*SendUserMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUserMsg not implemented")
}
func (UnimplementedMessageServer) SendRoomMsg(context.Context, *SendRoomMsgReq) (*SendRoomMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRoomMsg not implemented")
}
func (UnimplementedMessageServer) PostMoments(context.Context, *PostMomentsReq) (*PostMomentsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMoments not implemented")
}
func (UnimplementedMessageServer) mustEmbedUnimplementedMessageServer() {}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_SendUserMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendUserMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.message/SendUserMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendUserMsg(ctx, req.(*SendUserMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SendRoomMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRoomMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendRoomMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.message/SendRoomMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendRoomMsg(ctx, req.(*SendRoomMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_PostMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMomentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).PostMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.message/PostMoments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).PostMoments(ctx, req.(*PostMomentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendUserMsg",
			Handler:    _Message_SendUserMsg_Handler,
		},
		{
			MethodName: "SendRoomMsg",
			Handler:    _Message_SendRoomMsg_Handler,
		},
		{
			MethodName: "PostMoments",
			Handler:    _Message_PostMoments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
