// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: online.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlineUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GatewayAddr string `protobuf:"bytes,2,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
}

func (x *OnlineUserReq) Reset() {
	*x = OnlineUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUserReq) ProtoMessage() {}

func (x *OnlineUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUserReq.ProtoReflect.Descriptor instead.
func (*OnlineUserReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OnlineUserReq) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

type OnlineUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exp int64 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *OnlineUserResp) Reset() {
	*x = OnlineUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUserResp) ProtoMessage() {}

func (x *OnlineUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUserResp.ProtoReflect.Descriptor instead.
func (*OnlineUserResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{1}
}

func (x *OnlineUserResp) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type BatchOnlineUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIdList  []uint64 `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
	GatewayAddr string   `protobuf:"bytes,2,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
}

func (x *BatchOnlineUserReq) Reset() {
	*x = BatchOnlineUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchOnlineUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOnlineUserReq) ProtoMessage() {}

func (x *BatchOnlineUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOnlineUserReq.ProtoReflect.Descriptor instead.
func (*BatchOnlineUserReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{2}
}

func (x *BatchOnlineUserReq) GetUserIdList() []uint64 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

func (x *BatchOnlineUserReq) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

type BatchOnlineUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exp int64 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *BatchOnlineUserResp) Reset() {
	*x = BatchOnlineUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchOnlineUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOnlineUserResp) ProtoMessage() {}

func (x *BatchOnlineUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOnlineUserResp.ProtoReflect.Descriptor instead.
func (*BatchOnlineUserResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{3}
}

func (x *BatchOnlineUserResp) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type KeepAliveUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *KeepAliveUserReq) Reset() {
	*x = KeepAliveUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAliveUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveUserReq) ProtoMessage() {}

func (x *KeepAliveUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveUserReq.ProtoReflect.Descriptor instead.
func (*KeepAliveUserReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{4}
}

func (x *KeepAliveUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type KeepAliveUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exp int64 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *KeepAliveUserResp) Reset() {
	*x = KeepAliveUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAliveUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveUserResp) ProtoMessage() {}

func (x *KeepAliveUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveUserResp.ProtoReflect.Descriptor instead.
func (*KeepAliveUserResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{5}
}

func (x *KeepAliveUserResp) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type BatchKeepAliveUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIdList []uint64 `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
}

func (x *BatchKeepAliveUserReq) Reset() {
	*x = BatchKeepAliveUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchKeepAliveUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchKeepAliveUserReq) ProtoMessage() {}

func (x *BatchKeepAliveUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchKeepAliveUserReq.ProtoReflect.Descriptor instead.
func (*BatchKeepAliveUserReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{6}
}

func (x *BatchKeepAliveUserReq) GetUserIdList() []uint64 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

type BatchKeepAliveUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exp int64 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *BatchKeepAliveUserResp) Reset() {
	*x = BatchKeepAliveUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchKeepAliveUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchKeepAliveUserResp) ProtoMessage() {}

func (x *BatchKeepAliveUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchKeepAliveUserResp.ProtoReflect.Descriptor instead.
func (*BatchKeepAliveUserResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{7}
}

func (x *BatchKeepAliveUserResp) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type OfflineUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *OfflineUserReq) Reset() {
	*x = OfflineUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineUserReq) ProtoMessage() {}

func (x *OfflineUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineUserReq.ProtoReflect.Descriptor instead.
func (*OfflineUserReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{8}
}

func (x *OfflineUserReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type OfflineUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OfflineUserResp) Reset() {
	*x = OfflineUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineUserResp) ProtoMessage() {}

func (x *OfflineUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineUserResp.ProtoReflect.Descriptor instead.
func (*OfflineUserResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{9}
}

type BatchOfflineUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIdList []uint64 `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
}

func (x *BatchOfflineUserReq) Reset() {
	*x = BatchOfflineUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchOfflineUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOfflineUserReq) ProtoMessage() {}

func (x *BatchOfflineUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOfflineUserReq.ProtoReflect.Descriptor instead.
func (*BatchOfflineUserReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{10}
}

func (x *BatchOfflineUserReq) GetUserIdList() []uint64 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

type BatchOfflineUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BatchOfflineUserResp) Reset() {
	*x = BatchOfflineUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchOfflineUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOfflineUserResp) ProtoMessage() {}

func (x *BatchOfflineUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOfflineUserResp.ProtoReflect.Descriptor instead.
func (*BatchOfflineUserResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{11}
}

type GetUserGatewayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserGatewayReq) Reset() {
	*x = GetUserGatewayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserGatewayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGatewayReq) ProtoMessage() {}

func (x *GetUserGatewayReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGatewayReq.ProtoReflect.Descriptor instead.
func (*GetUserGatewayReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserGatewayReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserGatewayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayAddr string `protobuf:"bytes,1,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
}

func (x *GetUserGatewayResp) Reset() {
	*x = GetUserGatewayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserGatewayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGatewayResp) ProtoMessage() {}

func (x *GetUserGatewayResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGatewayResp.ProtoReflect.Descriptor instead.
func (*GetUserGatewayResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserGatewayResp) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

type BatchGetUserGatewayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIdList []uint64 `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
}

func (x *BatchGetUserGatewayReq) Reset() {
	*x = BatchGetUserGatewayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetUserGatewayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserGatewayReq) ProtoMessage() {}

func (x *BatchGetUserGatewayReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserGatewayReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserGatewayReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{14}
}

func (x *BatchGetUserGatewayReq) GetUserIdList() []uint64 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

type BatchGetUserGatewayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayAddrList []string `protobuf:"bytes,1,rep,name=gateway_addr_list,json=gatewayAddrList,proto3" json:"gateway_addr_list,omitempty"`
}

func (x *BatchGetUserGatewayResp) Reset() {
	*x = BatchGetUserGatewayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetUserGatewayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserGatewayResp) ProtoMessage() {}

func (x *BatchGetUserGatewayResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserGatewayResp.ProtoReflect.Descriptor instead.
func (*BatchGetUserGatewayResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{15}
}

func (x *BatchGetUserGatewayResp) GetGatewayAddrList() []string {
	if x != nil {
		return x.GatewayAddrList
	}
	return nil
}

type GetAllOnlineUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllOnlineUserReq) Reset() {
	*x = GetAllOnlineUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOnlineUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOnlineUserReq) ProtoMessage() {}

func (x *GetAllOnlineUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOnlineUserReq.ProtoReflect.Descriptor instead.
func (*GetAllOnlineUserReq) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{16}
}

type GetAllOnlineUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIdList []uint64 `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
}

func (x *GetAllOnlineUserResp) Reset() {
	*x = GetAllOnlineUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOnlineUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOnlineUserResp) ProtoMessage() {}

func (x *GetAllOnlineUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOnlineUserResp.ProtoReflect.Descriptor instead.
func (*GetAllOnlineUserResp) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllOnlineUserResp) GetUserIdList() []uint64 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

var File_online_proto protoreflect.FileDescriptor

var file_online_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x4b, 0x0a, 0x0d, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x22,
	0x22, 0x0a, 0x0e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x65, 0x78, 0x70, 0x22, 0x59, 0x0a, 0x12, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x22, 0x27,
	0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0x2b, 0x0a, 0x10, 0x4b, 0x65, 0x65, 0x70, 0x41,
	0x6c, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x11, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0x39, 0x0a, 0x15, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x16, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4b,
	0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65,
	0x78, 0x70, 0x22, 0x29, 0x0a, 0x0e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x11, 0x0a,
	0x0f, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x37, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x2c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x37, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x22, 0x3a, 0x0a, 0x16, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x17, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2a, 0x0a, 0x11, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x22, 0x38, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xe3, 0x04, 0x0a,
	0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0f,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x36, 0x0a, 0x0b, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3c, 0x0a, 0x0d, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x65, 0x70,
	0x41, 0x6c, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a,
	0x12, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x65,
	0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x13, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_online_proto_rawDescOnce sync.Once
	file_online_proto_rawDescData = file_online_proto_rawDesc
)

func file_online_proto_rawDescGZIP() []byte {
	file_online_proto_rawDescOnce.Do(func() {
		file_online_proto_rawDescData = protoimpl.X.CompressGZIP(file_online_proto_rawDescData)
	})
	return file_online_proto_rawDescData
}

var file_online_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_online_proto_goTypes = []interface{}{
	(*OnlineUserReq)(nil),           // 0: pb.OnlineUserReq
	(*OnlineUserResp)(nil),          // 1: pb.OnlineUserResp
	(*BatchOnlineUserReq)(nil),      // 2: pb.BatchOnlineUserReq
	(*BatchOnlineUserResp)(nil),     // 3: pb.BatchOnlineUserResp
	(*KeepAliveUserReq)(nil),        // 4: pb.KeepAliveUserReq
	(*KeepAliveUserResp)(nil),       // 5: pb.KeepAliveUserResp
	(*BatchKeepAliveUserReq)(nil),   // 6: pb.BatchKeepAliveUserReq
	(*BatchKeepAliveUserResp)(nil),  // 7: pb.BatchKeepAliveUserResp
	(*OfflineUserReq)(nil),          // 8: pb.OfflineUserReq
	(*OfflineUserResp)(nil),         // 9: pb.OfflineUserResp
	(*BatchOfflineUserReq)(nil),     // 10: pb.BatchOfflineUserReq
	(*BatchOfflineUserResp)(nil),    // 11: pb.BatchOfflineUserResp
	(*GetUserGatewayReq)(nil),       // 12: pb.GetUserGatewayReq
	(*GetUserGatewayResp)(nil),      // 13: pb.GetUserGatewayResp
	(*BatchGetUserGatewayReq)(nil),  // 14: pb.BatchGetUserGatewayReq
	(*BatchGetUserGatewayResp)(nil), // 15: pb.BatchGetUserGatewayResp
	(*GetAllOnlineUserReq)(nil),     // 16: pb.GetAllOnlineUserReq
	(*GetAllOnlineUserResp)(nil),    // 17: pb.GetAllOnlineUserResp
}
var file_online_proto_depIdxs = []int32{
	0,  // 0: pb.online.OnlineUser:input_type -> pb.OnlineUserReq
	2,  // 1: pb.online.BatchOnlineUser:input_type -> pb.BatchOnlineUserReq
	8,  // 2: pb.online.OfflineUser:input_type -> pb.OfflineUserReq
	10, // 3: pb.online.BatchOfflineUser:input_type -> pb.BatchOfflineUserReq
	4,  // 4: pb.online.KeepAliveUser:input_type -> pb.KeepAliveUserReq
	6,  // 5: pb.online.BatchKeepAliveUser:input_type -> pb.BatchKeepAliveUserReq
	12, // 6: pb.online.GetUserGateway:input_type -> pb.GetUserGatewayReq
	14, // 7: pb.online.BatchGetUserGateway:input_type -> pb.BatchGetUserGatewayReq
	16, // 8: pb.online.GetAllOnlineUser:input_type -> pb.GetAllOnlineUserReq
	1,  // 9: pb.online.OnlineUser:output_type -> pb.OnlineUserResp
	3,  // 10: pb.online.BatchOnlineUser:output_type -> pb.BatchOnlineUserResp
	9,  // 11: pb.online.OfflineUser:output_type -> pb.OfflineUserResp
	11, // 12: pb.online.BatchOfflineUser:output_type -> pb.BatchOfflineUserResp
	5,  // 13: pb.online.KeepAliveUser:output_type -> pb.KeepAliveUserResp
	7,  // 14: pb.online.BatchKeepAliveUser:output_type -> pb.BatchKeepAliveUserResp
	13, // 15: pb.online.GetUserGateway:output_type -> pb.GetUserGatewayResp
	15, // 16: pb.online.BatchGetUserGateway:output_type -> pb.BatchGetUserGatewayResp
	17, // 17: pb.online.GetAllOnlineUser:output_type -> pb.GetAllOnlineUserResp
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_online_proto_init() }
func file_online_proto_init() {
	if File_online_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_online_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchOnlineUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchOnlineUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAliveUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAliveUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchKeepAliveUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchKeepAliveUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchOfflineUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchOfflineUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserGatewayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserGatewayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetUserGatewayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetUserGatewayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOnlineUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOnlineUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_online_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_online_proto_goTypes,
		DependencyIndexes: file_online_proto_depIdxs,
		MessageInfos:      file_online_proto_msgTypes,
	}.Build()
	File_online_proto = out.File
	file_online_proto_rawDesc = nil
	file_online_proto_goTypes = nil
	file_online_proto_depIdxs = nil
}
