// Code generated by goctl. DO NOT EDIT!
// Source: msg_send.proto

package server

import (
	"context"

	"github.com/wymli/bcsns/app/msg_send/internal/logic"
	"github.com/wymli/bcsns/app/msg_send/internal/svc"
	"github.com/wymli/bcsns/app/msg_send/pb"
)

type MsgSendServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMsgSendServer
}

func NewMsgSendServer(svcCtx *svc.ServiceContext) *MsgSendServer {
	return &MsgSendServer{
		svcCtx: svcCtx,
	}
}

func (s *MsgSendServer) SendUserMsg(ctx context.Context, in *pb.SendUserMsgReq) (*pb.SendUserMsgResp, error) {
	l := logic.NewSendUserMsgLogic(ctx, s.svcCtx)
	return l.SendUserMsg(in)
}

func (s *MsgSendServer) SendRoomMsg(ctx context.Context, in *pb.SendRoomMsgReq) (*pb.SendRoomMsgResp, error) {
	l := logic.NewSendRoomMsgLogic(ctx, s.svcCtx)
	return l.SendRoomMsg(in)
}

func (s *MsgSendServer) PostMoments(ctx context.Context, in *pb.PostMomentsReq) (*pb.PostMomentsResp, error) {
	l := logic.NewPostMomentsLogic(ctx, s.svcCtx)
	return l.PostMoments(in)
}
