// Code generated by goctl. DO NOT EDIT!
// Source: authx.proto

package auth

import (
	"context"

	"github.com/wymli/bcsns/app/auth/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClearTokenReq     = pb.ClearTokenReq
	ClearTokenResp    = pb.ClearTokenResp
	GenerateTokenReq  = pb.GenerateTokenReq
	GenerateTokenResp = pb.GenerateTokenResp
	ValidateTokenReq  = pb.ValidateTokenReq
	ValidateTokenResp = pb.ValidateTokenResp

	Auth interface {
		//  生成token，只针对用户服务开放访问
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
		//  清除token，只针对用户服务开放访问
		ClearToken(ctx context.Context, in *ClearTokenReq, opts ...grpc.CallOption) (*ClearTokenResp, error)
		//  验证Token ，只很对用户服务、授权服务api开放
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

//  生成token，只针对用户服务开放访问
func (m *defaultAuth) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

//  清除token，只针对用户服务开放访问
func (m *defaultAuth) ClearToken(ctx context.Context, in *ClearTokenReq, opts ...grpc.CallOption) (*ClearTokenResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.ClearToken(ctx, in, opts...)
}

//  验证Token ，只很对用户服务、授权服务api开放
func (m *defaultAuth) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}
