// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: bc_proxy.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnChainUserMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 内容类型
	SendMsgId   int64  `protobuf:"varint,2,opt,name=send_msg_id,json=sendMsgId,proto3" json:"send_msg_id,omitempty"`    // 用于服务端去重,客户端去重
	ServerMsgId int64  `protobuf:"varint,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	SendUserId  uint64 `protobuf:"varint,4,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"` // sender user id
	RecvUserId  uint64 `protobuf:"varint,5,opt,name=recv_user_id,json=recvUserId,proto3" json:"recv_user_id,omitempty"` // recver user id
	Data        []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                  // payload body
	IsTest      *bool  `protobuf:"varint,7,opt,name=is_test,json=isTest,proto3,oneof" json:"is_test,omitempty"`         // 是否测试
}

func (x *OnChainUserMsgReq) Reset() {
	*x = OnChainUserMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainUserMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainUserMsgReq) ProtoMessage() {}

func (x *OnChainUserMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainUserMsgReq.ProtoReflect.Descriptor instead.
func (*OnChainUserMsgReq) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *OnChainUserMsgReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *OnChainUserMsgReq) GetSendMsgId() int64 {
	if x != nil {
		return x.SendMsgId
	}
	return 0
}

func (x *OnChainUserMsgReq) GetServerMsgId() int64 {
	if x != nil {
		return x.ServerMsgId
	}
	return 0
}

func (x *OnChainUserMsgReq) GetSendUserId() uint64 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *OnChainUserMsgReq) GetRecvUserId() uint64 {
	if x != nil {
		return x.RecvUserId
	}
	return 0
}

func (x *OnChainUserMsgReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OnChainUserMsgReq) GetIsTest() bool {
	if x != nil && x.IsTest != nil {
		return *x.IsTest
	}
	return false
}

type OnChainUserMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnChainUserMsgResp) Reset() {
	*x = OnChainUserMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainUserMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainUserMsgResp) ProtoMessage() {}

func (x *OnChainUserMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainUserMsgResp.ProtoReflect.Descriptor instead.
func (*OnChainUserMsgResp) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{1}
}

type OnChainRoomMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 内容类型
	SendMsgId   int64  `protobuf:"varint,2,opt,name=send_msg_id,json=sendMsgId,proto3" json:"send_msg_id,omitempty"`    // 用于服务端去重,客户端去重
	ServerMsgId int64  `protobuf:"varint,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	SendUserId  uint64 `protobuf:"varint,4,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"` // sender user id
	RoomId      uint64 `protobuf:"varint,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`               // chat room id
	Data        []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                  // payload body
	IsTest      *bool  `protobuf:"varint,7,opt,name=is_test,json=isTest,proto3,oneof" json:"is_test,omitempty"`         // 是否测试
}

func (x *OnChainRoomMsgReq) Reset() {
	*x = OnChainRoomMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainRoomMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainRoomMsgReq) ProtoMessage() {}

func (x *OnChainRoomMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainRoomMsgReq.ProtoReflect.Descriptor instead.
func (*OnChainRoomMsgReq) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *OnChainRoomMsgReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *OnChainRoomMsgReq) GetSendMsgId() int64 {
	if x != nil {
		return x.SendMsgId
	}
	return 0
}

func (x *OnChainRoomMsgReq) GetServerMsgId() int64 {
	if x != nil {
		return x.ServerMsgId
	}
	return 0
}

func (x *OnChainRoomMsgReq) GetSendUserId() uint64 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *OnChainRoomMsgReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *OnChainRoomMsgReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OnChainRoomMsgReq) GetIsTest() bool {
	if x != nil && x.IsTest != nil {
		return *x.IsTest
	}
	return false
}

type OnChainRoomMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnChainRoomMsgResp) Reset() {
	*x = OnChainRoomMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainRoomMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainRoomMsgResp) ProtoMessage() {}

func (x *OnChainRoomMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainRoomMsgResp.ProtoReflect.Descriptor instead.
func (*OnChainRoomMsgResp) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{3}
}

type OnChainMomentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType     string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`          // 内容类型
	SendMomentsId   int64  `protobuf:"varint,2,opt,name=send_moments_id,json=sendMomentsId,proto3" json:"send_moments_id,omitempty"` // 用于服务端去重,客户端去重
	ServerMomentsId int64  `protobuf:"varint,3,opt,name=server_moments_id,json=serverMomentsId,proto3" json:"server_moments_id,omitempty"`
	UserId          uint64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // sender user id
	Data            []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                          // payload body
	IsTest          *bool  `protobuf:"varint,6,opt,name=is_test,json=isTest,proto3,oneof" json:"is_test,omitempty"` // 是否测试
}

func (x *OnChainMomentsReq) Reset() {
	*x = OnChainMomentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainMomentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainMomentsReq) ProtoMessage() {}

func (x *OnChainMomentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainMomentsReq.ProtoReflect.Descriptor instead.
func (*OnChainMomentsReq) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *OnChainMomentsReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *OnChainMomentsReq) GetSendMomentsId() int64 {
	if x != nil {
		return x.SendMomentsId
	}
	return 0
}

func (x *OnChainMomentsReq) GetServerMomentsId() int64 {
	if x != nil {
		return x.ServerMomentsId
	}
	return 0
}

func (x *OnChainMomentsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OnChainMomentsReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OnChainMomentsReq) GetIsTest() bool {
	if x != nil && x.IsTest != nil {
		return *x.IsTest
	}
	return false
}

type OnChainMomentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnChainMomentsResp) Reset() {
	*x = OnChainMomentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainMomentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainMomentsResp) ProtoMessage() {}

func (x *OnChainMomentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainMomentsResp.ProtoReflect.Descriptor instead.
func (*OnChainMomentsResp) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{5}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 内容类型
	ServerMsgId int64  `protobuf:"varint,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	SendUserId  uint64 `protobuf:"varint,4,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"` // sender user id
	RecvId      uint64 `protobuf:"varint,5,opt,name=recv_id,json=recvId,proto3" json:"recv_id,omitempty"`               // recver user id or room id
	Data        []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                  // payload body
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *Msg) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Msg) GetServerMsgId() int64 {
	if x != nil {
		return x.ServerMsgId
	}
	return 0
}

func (x *Msg) GetSendUserId() uint64 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *Msg) GetRecvId() uint64 {
	if x != nil {
		return x.RecvId
	}
	return 0
}

func (x *Msg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PullRoomMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     uint64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StartBlock int64  `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock   int64  `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
}

func (x *PullRoomMsgReq) Reset() {
	*x = PullRoomMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullRoomMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRoomMsgReq) ProtoMessage() {}

func (x *PullRoomMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRoomMsgReq.ProtoReflect.Descriptor instead.
func (*PullRoomMsgReq) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *PullRoomMsgReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PullRoomMsgReq) GetStartBlock() int64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *PullRoomMsgReq) GetEndBlock() int64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

type PullRoomMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgList []*Msg `protobuf:"bytes,1,rep,name=msg_list,json=msgList,proto3" json:"msg_list,omitempty"`
}

func (x *PullRoomMsgResp) Reset() {
	*x = PullRoomMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullRoomMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRoomMsgResp) ProtoMessage() {}

func (x *PullRoomMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRoomMsgResp.ProtoReflect.Descriptor instead.
func (*PullRoomMsgResp) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *PullRoomMsgResp) GetMsgList() []*Msg {
	if x != nil {
		return x.MsgList
	}
	return nil
}

type PullUserMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUid    uint64 `protobuf:"varint,1,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	RecvUid    uint64 `protobuf:"varint,2,opt,name=recv_uid,json=recvUid,proto3" json:"recv_uid,omitempty"`
	StartBlock int64  `protobuf:"varint,3,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock   int64  `protobuf:"varint,4,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
}

func (x *PullUserMsgReq) Reset() {
	*x = PullUserMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullUserMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullUserMsgReq) ProtoMessage() {}

func (x *PullUserMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullUserMsgReq.ProtoReflect.Descriptor instead.
func (*PullUserMsgReq) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *PullUserMsgReq) GetFromUid() uint64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *PullUserMsgReq) GetRecvUid() uint64 {
	if x != nil {
		return x.RecvUid
	}
	return 0
}

func (x *PullUserMsgReq) GetStartBlock() int64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *PullUserMsgReq) GetEndBlock() int64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

type PullUserMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgList []*Msg `protobuf:"bytes,1,rep,name=msg_list,json=msgList,proto3" json:"msg_list,omitempty"`
}

func (x *PullUserMsgResp) Reset() {
	*x = PullUserMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bc_proxy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullUserMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullUserMsgResp) ProtoMessage() {}

func (x *PullUserMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_bc_proxy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullUserMsgResp.ProtoReflect.Descriptor instead.
func (*PullUserMsgResp) Descriptor() ([]byte, []int) {
	return file_bc_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *PullUserMsgResp) GetMsgList() []*Msg {
	if x != nil {
		return x.MsgList
	}
	return nil
}

var File_bc_proxy_proto protoreflect.FileDescriptor

var file_bc_proxy_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xfc, 0x01, 0x0a, 0x11, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x73,
	0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x76, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x74, 0x65,
	0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x69, 0x73, 0x54, 0x65,
	0x73, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x22, 0x14, 0x0a, 0x12, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0xf3, 0x01, 0x0a, 0x11, 0x4f, 0x6e, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1e, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x69, 0x73, 0x54, 0x65, 0x73, 0x74, 0x88, 0x01,
	0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a,
	0x12, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x22, 0xe1, 0x01, 0x0a, 0x11, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a,
	0x07, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x06, 0x69, 0x73, 0x54, 0x65, 0x73, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x69, 0x73, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4f, 0x6e, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x9b, 0x01,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x65, 0x63, 0x76, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x67, 0x0a, 0x0e, 0x50,
	0x75, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x35, 0x0a, 0x0f, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x73, 0x67, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x0e,
	0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x19,
	0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x76, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x65, 0x63,
	0x76, 0x55, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x22, 0x35, 0x0a, 0x0f, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67,
	0x52, 0x07, 0x6d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xf2, 0x02, 0x0a, 0x08, 0x62, 0x63,
	0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x3f, 0x0a, 0x0e, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x6e,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x4f, 0x6e, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4f,
	0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x6f,
	0x6d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x4f, 0x6e, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x0b, 0x50, 0x75, 0x6c,
	0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75,
	0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x6d, 0x73, 0x67, 0x12, 0x50, 0x0a, 0x0b,
	0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d, 0x73, 0x67, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bc_proxy_proto_rawDescOnce sync.Once
	file_bc_proxy_proto_rawDescData = file_bc_proxy_proto_rawDesc
)

func file_bc_proxy_proto_rawDescGZIP() []byte {
	file_bc_proxy_proto_rawDescOnce.Do(func() {
		file_bc_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_bc_proxy_proto_rawDescData)
	})
	return file_bc_proxy_proto_rawDescData
}

var file_bc_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bc_proxy_proto_goTypes = []interface{}{
	(*OnChainUserMsgReq)(nil),  // 0: pb.OnChainUserMsgReq
	(*OnChainUserMsgResp)(nil), // 1: pb.OnChainUserMsgResp
	(*OnChainRoomMsgReq)(nil),  // 2: pb.OnChainRoomMsgReq
	(*OnChainRoomMsgResp)(nil), // 3: pb.OnChainRoomMsgResp
	(*OnChainMomentsReq)(nil),  // 4: pb.OnChainMomentsReq
	(*OnChainMomentsResp)(nil), // 5: pb.OnChainMomentsResp
	(*Msg)(nil),                // 6: pb.Msg
	(*PullRoomMsgReq)(nil),     // 7: pb.PullRoomMsgReq
	(*PullRoomMsgResp)(nil),    // 8: pb.PullRoomMsgResp
	(*PullUserMsgReq)(nil),     // 9: pb.PullUserMsgReq
	(*PullUserMsgResp)(nil),    // 10: pb.PullUserMsgResp
}
var file_bc_proxy_proto_depIdxs = []int32{
	6,  // 0: pb.PullRoomMsgResp.msg_list:type_name -> pb.Msg
	6,  // 1: pb.PullUserMsgResp.msg_list:type_name -> pb.Msg
	0,  // 2: pb.bc_proxy.OnChainUserMsg:input_type -> pb.OnChainUserMsgReq
	2,  // 3: pb.bc_proxy.OnChainRoomMsg:input_type -> pb.OnChainRoomMsgReq
	4,  // 4: pb.bc_proxy.OnChainMoments:input_type -> pb.OnChainMomentsReq
	7,  // 5: pb.bc_proxy.PullRoomMsg:input_type -> pb.PullRoomMsgReq
	9,  // 6: pb.bc_proxy.PullUserMsg:input_type -> pb.PullUserMsgReq
	1,  // 7: pb.bc_proxy.OnChainUserMsg:output_type -> pb.OnChainUserMsgResp
	3,  // 8: pb.bc_proxy.OnChainRoomMsg:output_type -> pb.OnChainRoomMsgResp
	5,  // 9: pb.bc_proxy.OnChainMoments:output_type -> pb.OnChainMomentsResp
	8,  // 10: pb.bc_proxy.PullRoomMsg:output_type -> pb.PullRoomMsgResp
	10, // 11: pb.bc_proxy.PullUserMsg:output_type -> pb.PullUserMsgResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_bc_proxy_proto_init() }
func file_bc_proxy_proto_init() {
	if File_bc_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bc_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainUserMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainUserMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainRoomMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainRoomMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainMomentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainMomentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullRoomMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullRoomMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullUserMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bc_proxy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullUserMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bc_proxy_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_bc_proxy_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_bc_proxy_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bc_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bc_proxy_proto_goTypes,
		DependencyIndexes: file_bc_proxy_proto_depIdxs,
		MessageInfos:      file_bc_proxy_proto_msgTypes,
	}.Build()
	File_bc_proxy_proto = out.File
	file_bc_proxy_proto_rawDesc = nil
	file_bc_proxy_proto_goTypes = nil
	file_bc_proxy_proto_depIdxs = nil
}
