// Code generated by goctl. DO NOT EDIT!
// Source: authx.proto

package server

import (
	"context"

	"github.com/wymli/bcsns/app/auth_rpc/internal/logic"
	"github.com/wymli/bcsns/app/auth_rpc/internal/svc"
	"github.com/wymli/bcsns/app/auth_rpc/pb"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

//  生成token，只针对用户服务开放访问
func (s *AuthServer) GenerateToken(ctx context.Context, in *pb.GenerateTokenReq) (*pb.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

//  清除token，只针对用户服务开放访问
func (s *AuthServer) ClearToken(ctx context.Context, in *pb.ClearTokenReq) (*pb.ClearTokenResp, error) {
	l := logic.NewClearTokenLogic(ctx, s.svcCtx)
	return l.ClearToken(in)
}

//  验证Token ，只很对用户服务、授权服务api开放
func (s *AuthServer) ValidateToken(ctx context.Context, in *pb.ValidateTokenReq) (*pb.ValidateTokenResp, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}
