// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: msg_send.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgSendClient is the client API for MsgSend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgSendClient interface {
	SendUserMsg(ctx context.Context, in *SendUserMsgReq, opts ...grpc.CallOption) (*SendUserMsgResp, error)
	SendRoomMsg(ctx context.Context, in *SendRoomMsgReq, opts ...grpc.CallOption) (*SendRoomMsgResp, error)
	PostMoments(ctx context.Context, in *PostMomentsReq, opts ...grpc.CallOption) (*PostMomentsResp, error)
}

type msgSendClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgSendClient(cc grpc.ClientConnInterface) MsgSendClient {
	return &msgSendClient{cc}
}

func (c *msgSendClient) SendUserMsg(ctx context.Context, in *SendUserMsgReq, opts ...grpc.CallOption) (*SendUserMsgResp, error) {
	out := new(SendUserMsgResp)
	err := c.cc.Invoke(ctx, "/pb.MsgSend/SendUserMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgSendClient) SendRoomMsg(ctx context.Context, in *SendRoomMsgReq, opts ...grpc.CallOption) (*SendRoomMsgResp, error) {
	out := new(SendRoomMsgResp)
	err := c.cc.Invoke(ctx, "/pb.MsgSend/SendRoomMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgSendClient) PostMoments(ctx context.Context, in *PostMomentsReq, opts ...grpc.CallOption) (*PostMomentsResp, error) {
	out := new(PostMomentsResp)
	err := c.cc.Invoke(ctx, "/pb.MsgSend/PostMoments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgSendServer is the server API for MsgSend service.
// All implementations must embed UnimplementedMsgSendServer
// for forward compatibility
type MsgSendServer interface {
	SendUserMsg(context.Context, *SendUserMsgReq) (*SendUserMsgResp, error)
	SendRoomMsg(context.Context, *SendRoomMsgReq) (*SendRoomMsgResp, error)
	PostMoments(context.Context, *PostMomentsReq) (*PostMomentsResp, error)
	mustEmbedUnimplementedMsgSendServer()
}

// UnimplementedMsgSendServer must be embedded to have forward compatible implementations.
type UnimplementedMsgSendServer struct {
}

func (UnimplementedMsgSendServer) SendUserMsg(context.Context, *SendUserMsgReq) (*SendUserMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUserMsg not implemented")
}
func (UnimplementedMsgSendServer) SendRoomMsg(context.Context, *SendRoomMsgReq) (*SendRoomMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRoomMsg not implemented")
}
func (UnimplementedMsgSendServer) PostMoments(context.Context, *PostMomentsReq) (*PostMomentsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMoments not implemented")
}
func (UnimplementedMsgSendServer) mustEmbedUnimplementedMsgSendServer() {}

// UnsafeMsgSendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgSendServer will
// result in compilation errors.
type UnsafeMsgSendServer interface {
	mustEmbedUnimplementedMsgSendServer()
}

func RegisterMsgSendServer(s grpc.ServiceRegistrar, srv MsgSendServer) {
	s.RegisterService(&MsgSend_ServiceDesc, srv)
}

func _MsgSend_SendUserMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgSendServer).SendUserMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MsgSend/SendUserMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgSendServer).SendUserMsg(ctx, req.(*SendUserMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgSend_SendRoomMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRoomMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgSendServer).SendRoomMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MsgSend/SendRoomMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgSendServer).SendRoomMsg(ctx, req.(*SendRoomMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgSend_PostMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMomentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgSendServer).PostMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MsgSend/PostMoments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgSendServer).PostMoments(ctx, req.(*PostMomentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgSend_ServiceDesc is the grpc.ServiceDesc for MsgSend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgSend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MsgSend",
	HandlerType: (*MsgSendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendUserMsg",
			Handler:    _MsgSend_SendUserMsg_Handler,
		},
		{
			MethodName: "SendRoomMsg",
			Handler:    _MsgSend_SendRoomMsg_Handler,
		},
		{
			MethodName: "PostMoments",
			Handler:    _MsgSend_PostMoments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg_send.proto",
}
